main: me.shurikennen.SiteBDiscordSync
name: SiteBDiscordSync
version: 1.0.0
authors: [Shurikennen]
api-version: 1.20
depend: [Essentials]
libraries:
  - net.dv8tion:JDA:5.0.0-beta.24
  - net.kyori:adventure-text-serializer-legacy:4.17.0